# Generated by Django 3.2.5 on 2021-10-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guests_can_pause',
            new_name='guest_can_pause',
        ),
    ]
